
PATH:
  DATASET_DIR: 'dataset/'
  PKL_PATH: 'dataset/database.pkl'

INFO:
  PICTURE_PROMPT: 'Seamless Attendance Tracking with Face Check-In: A Python Web App Revolutionizing Marking Attendance.'
  WEBCAM_PROMPT: 'This app recognizes faces in a live video stream and marks your Attendance.Allow access to your webcam.'